site_name: GapWorks 东方Project主题服务器组

theme:
  name: material
  language: zh
  palette:
      primary: deep purple

  features:
  - navigation.top
  - navigation.tabs
  - navigation.indexes
  - search.suggest
  - content.code.copy
  - content.tooltips
  icon:
    annotation: material/plus-circle

plugins:
  - search
  - blog
  - tags

nav:
  - 主页: index.md
  - 玩家指南:
    - 前言: index2.md 
    - 服务器规则: page1.md
    - 加入服务器: page2.md
    - 内容概览: page3.md
    - 常见FAQ: page4.md
  - Touhou Mcbattle Wiki: wiki.md
  - 小游戏服: xyx.md
  - 生存服: sc.md

markdown_extensions:
- attr_list

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html

copyright: Copyright &copy; 2020 - 2024 GapWorks